// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy2OX4-a5dKR8hHfDOFUpIdc4wQfwxTqE',
    appId: '1:251450547660:web:0a8d4c3135726009e4d169',
    messagingSenderId: '251450547660',
    projectId: 'kzmusic-55d18',
    authDomain: 'kzmusic-55d18.firebaseapp.com',
    storageBucket: 'kzmusic-55d18.firebasestorage.app',
    measurementId: 'G-P2Z7C1E0QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCRGOdzwBrJzzTDT88bgNSt-bEVeGu8o',
    appId: '1:251450547660:android:b3c41098bfca0e0ee4d169',
    messagingSenderId: '251450547660',
    projectId: 'kzmusic-55d18',
    storageBucket: 'kzmusic-55d18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEsA2F_eswGFzzhqOce00tVV5DydYMVIg',
    appId: '1:251450547660:ios:7279beb82853636ee4d169',
    messagingSenderId: '251450547660',
    projectId: 'kzmusic-55d18',
    storageBucket: 'kzmusic-55d18.firebasestorage.app',
    androidClientId: '251450547660-cf3peb4nemlmqntqi6h5r87ku9fsp3if.apps.googleusercontent.com',
    iosClientId: '251450547660-tt4sm3g637g0qj0aa5vj0kpde49ao42n.apps.googleusercontent.com',
    iosBundleId: 'com.example.kzmusicCrossPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEsA2F_eswGFzzhqOce00tVV5DydYMVIg',
    appId: '1:251450547660:ios:7279beb82853636ee4d169',
    messagingSenderId: '251450547660',
    projectId: 'kzmusic-55d18',
    storageBucket: 'kzmusic-55d18.firebasestorage.app',
    androidClientId: '251450547660-cf3peb4nemlmqntqi6h5r87ku9fsp3if.apps.googleusercontent.com',
    iosClientId: '251450547660-tt4sm3g637g0qj0aa5vj0kpde49ao42n.apps.googleusercontent.com',
    iosBundleId: 'com.example.kzmusicCrossPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy2OX4-a5dKR8hHfDOFUpIdc4wQfwxTqE',
    appId: '1:251450547660:web:c57f0db8b1acfed8e4d169',
    messagingSenderId: '251450547660',
    projectId: 'kzmusic-55d18',
    authDomain: 'kzmusic-55d18.firebaseapp.com',
    storageBucket: 'kzmusic-55d18.firebasestorage.app',
    measurementId: 'G-9J1MYLP41E',
  );
}
