// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3o24EUO7BfUdp6_l8d4vz8eIDjAdFVzc',
    appId: '1:251450547660:web:0049acdd303a0c97e4d169',
    messagingSenderId: '251450547660',
    projectId: 'kzmusic-55d18',
    authDomain: 'kzmusic-55d18.firebaseapp.com',
    storageBucket: 'kzmusic-55d18.firebasestorage.app',
    measurementId: 'G-TQBGXJ3D2X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU_VeDIF-M86oRJoVRG8MEjM2ASW55-BI',
    appId: '1:251450547660:ios:8185d34b931c7b4be4d169',
    messagingSenderId: '251450547660',
    projectId: 'kzmusic-55d18',
    storageBucket: 'kzmusic-55d18.firebasestorage.app',
    androidClientId: '251450547660-3mo8irc1q63s1h9l8bc4e509vrdte60k.apps.googleusercontent.com',
    iosClientId: '251450547660-dq2sphv9lrmi471vpjvam428td7h9bvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kzmusicCrossPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU_VeDIF-M86oRJoVRG8MEjM2ASW55-BI',
    appId: '1:251450547660:ios:8185d34b931c7b4be4d169',
    messagingSenderId: '251450547660',
    projectId: 'kzmusic-55d18',
    storageBucket: 'kzmusic-55d18.firebasestorage.app',
    androidClientId: '251450547660-3mo8irc1q63s1h9l8bc4e509vrdte60k.apps.googleusercontent.com',
    iosClientId: '251450547660-dq2sphv9lrmi471vpjvam428td7h9bvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kzmusicCrossPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3o24EUO7BfUdp6_l8d4vz8eIDjAdFVzc',
    appId: '1:251450547660:web:c619022e84c8c44de4d169',
    messagingSenderId: '251450547660',
    projectId: 'kzmusic-55d18',
    authDomain: 'kzmusic-55d18.firebaseapp.com',
    storageBucket: 'kzmusic-55d18.firebasestorage.app',
    measurementId: 'G-M2W0DDS8CR',
  );

}